### ISSUE TITLE
Problem statement

### ISSUE THREAD

**Issue by kangshwan** [GaYoung2/Software_Engineering#1]
요구사항:
풀고자 하는 문제:

**Comment by kangshwan** [comment]
## 요구사항:
> Problem:
* 카페 및 패스트푸드점에 가면 주문하기 전에 자리 유무를 확인하기 위해 매장을 돌아다님
* 매장에 자리가 없으면 다른 카페에 감
> 대상:
* 매장에 오는 고객 - 입구에서 부터 자리 유무를 빠르게 확인 할 수 있어 시간절약 가능
* 매장 - 음식점의 경우 손님이 떠난 자리 빠르게 파악 가능.
> 제공하는 기능:
* CCTV를 이용한 자리 확인 및 관리 서비스
* 자리 유무를 한눈에 볼 수 있게 제공하는 인터페이스
* 나아가 자리를 못정하는 시간대 예약이 아닌 시간+자리 통합 예약 서비스
> 주의사항:
* 각자 초상권이 존재하므로, 최소한으로 데이터 저장
* 실시간으로 좌석 확인을 해야하기 때문에 빠른 처리속도 필요

**Comment by kangshwan** [comment]
@GaYoung2 빨리 봐주세요

**Comment by GaYoung2** [comment]
전종원 : 오늘날 현대인들이 카페나 식당을 방문하면 주문전에 반드시 하는 행동이 있다. 바로 좌석을 확인하는 것이다. 일행이 다 앉을 수 있는 좌석이 없다면 다른 카페를 찾아 떠난다. 실시간 영상을 통한 좌석 확인 서비스는 카페나 식당에 설치된 카메라를 통해 좌석의 현재 사용여부를 판별하여 웹 사이트에 좌석의 사용 현황을 UI로 띄어주는 서비스를 제공한다. 서비스에 가입된 카페나 식당은 소비자가 굳이 방문하지 않더라도 웹사이트에 등록된 해당 카페를 클릭만 하면 좌석의 사용현황을 한눈에 확인 할 수 있다.

**Comment by GaYoung2** [comment]
김가영: nonfunctional :

1,사용자는 웹과 앱 두가지 모두 다 사용하여 서비스를 이용 할 수 있어야 한다.
2.사용자가 사용할때 빠르게 좌석 현황을 알려줘야 한다.
3.서비스를 사용하는 가게가 추가될 때 마다 업데이트를 해 줘야한다.

**Comment by GaYoung2** [comment]
functional:  @kangshwan @seowoobean 
1.서비스 소개
2.요구사항(problem)
3.제공하는 기능
nonfunctional: @GaYoung2 @jeonjw25 
1.서비스를 제공할 대상 (가게주인, 가게사용자)
2.주의사항
3.제공할 속도
4.업데이트가 되는지 안되는지
5.외부시스템(시시티비)
6.웹과 앱 두가지 모두 다 사용 가능

**Comment by kangshwan** [comment]
ㅁㅁㅁ는 좌석을 활용하는 모든 시설의 빈자리를 파악하는 서비스이다.  
ㅁㅁㅁ는 영상정보(CCTV)를 활용하여 자동으로 빈자리를 파악하여 고객들에게 제공한다. 
ㅁㅁㅁ는 인공지능을 이용하여 좌석의 사용 여부를 단순한 사람의 유무가 아닌 실제 사람이 판단한 것 처럼 정확히 빈좌석을 찾아낸다.(예: 잠시 비운 자리(화장실, 흡연 등)는 빈 좌석으로 취급하지 않음)
`ㅁㅁㅁ는 사람의 유무 뿐만 아니라, 인공지능을 이용하여 잠시 자리를 비운 경우에는 빈자리로 파악하지 않게한다. 
ㅁㅁㅁ는 빈자리 여부를 인공지능으로 파악하여 실제 사람이 눈으로 빈자리르 파악한것같은 정확성을 갖고잇따.`
ㅁㅁㅁ은 현재 좌석정보를 간략화 하여 현재 빈자리가 어디있는지 보여준다.
`ㅁㅁㅁ은 영상 내부의 좌석들의 정보를 쉽게 확인할 수 있는 간단한 논리적 정보로 나타내어 준다. `

* 추가적으로 생각해 본것
* 예약시스템(한 자리에 대해서 많은 사람들이 예약 가능)
* 내가 예약한 자리가 아닌 다른 빈 자리가 생길 경우 예약 시스템에서 가장 최상단에 잇는 사람에게 물어봄(그 빈자리를 쓸것인지)

**Comment by seowoobean** [comment]
서비스 대상 : 좌석을 활용하는 시설
1. 영상 정보 제공만으로 서비스를 제공할 수 있어야 한다.

서비스 사용자 : 시설을 이용하는 소비자
가게를 이용하고자하는 모든 고객들이 이 서비스를 이용 할 수 있어야 한다.
1. 개발되는 웹페이지는 모바일로 접근시에도 깔끔한 UI를 유지해야 한다.
2. 웹으로 확인한 좌석 상태가 실제 좌석 현황과 오차가 없어야 한다.
3. 가게 운영시간이 아닐때에는 사용자에게 운영시간이 아님임을 정확히 알릴 수 있어야 한다.
업데이트 혹은 버전관리:
4. 좌석의 배치나 수가 변경되었을때 웹페이지에 빠른 업데이트가 필요하다.
추가적인 소프트웨어:
5. 가게 내부에 좌석을 확인할 CCTV가 있어야 한다.
~6. 실시간으로 좌석 현황을 전달해야 하기 때문에 빠른 처리속도가 필요하다.~

주의사항:
7. 주의사항으로 사용 현황을 씨씨티비로 확인하기 때문에, 고객의 초상권을 해치지 않기 위해 영상 데이터의 저장을 최소화 해야 한다.
저희겁니다.

**Comment by jeonjw25** [comment]
서비스 대상 : 좌석을 활용하는 시설  

1. 영상 정보 제공만으로 서비스를 제공할 수 있어야 한다.(서비스 등록절차가 간단해야 한다.)
2. Client 측에서 웹페이지의 좌석 배치도의 업데이트를 요구시 빠른 업데이트가 이루어져야 한다.

**Comment by GaYoung2** [comment]
좌석 확인 시스템,Seat to Sit(이하 StS)

  StS는 좌석을 활용하는 모든 시설의 빈자리를 파악하는 서비스이다. StS는 각 시설의 CCTV를 활용하여 현재의 시설 영상을 통해 실제 가게의 좌석을 파악하는 서비스 입니다.
  StS는 영상정보(CCTV)를 활용하여 자동으로 빈자리를 파악하여 시설를 이용하고자 하는 고객들에게 제공한다. StS는 인공지능을 이용하여 좌석의 사용 여부를 단순한 사람의 유무가 아닌 실제 사람이 판단한 것 처럼 정확히 빈좌석을 찾아낸다.(예: 잠시 비운 자리(화장실, 흡연 등)는 빈 좌석으로 취급하지 않음) StS는 현재 좌석정보를 간략화 하여 현재 빈자리가 어디있는지 보여준다. StS는 웹과 앱을 통해 좌석 정보를 제공해준다.  또한 사용자가 지정한 시설의 빈자리 알림을 해준다. 웹은 시설 검색 및 등록된 시설을 보여주고, 각 시설을 눌렀을때 선택한 시설에 대한 실시간 좌석을 보여준다.

**Comment by GaYoung2** [comment]
Quality requirements
서비스 대상은 좌석을 활용하는 모든 시설이다.
서비스 사용자는 시설을 사용하는 모든 고객이다.
StS는 시설의 모든 좌석 정보가 담겨있는 영상 정보 제공만으로 서비스를 제공할 수 있어야 한다.
웹에서 확인한 좌석 상태가 실제 좌석 현황과 오차가 없어야 한다.
가게 운영시간이 아닐때에는 사용자에게 운영시간이 아님임을 정확히 알릴 수 있어야 한다.
좌석의 배치나 수가 변경되었을때 웹페이지에 빠른 업데이트가 필요하다.[업데이트 혹은 버전관리]
가게 내부에 좌석을 확인할 CCTV가 있어야 한다.[추가적인 하드웨어]
